[package]
name = 'Portrait'
version = '1.0.0'

[addresses]
flex_token = "0xcafe"

[dependencies]
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }
TokenObjects = { local = "../framework" }