[package]
name = 'Coins'
version = '1.0.0'

[addresses]
#flex_token = "0xcafe"
flex_token = "_"

[dependencies]
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }
TokenObjects = { local = "../framework" }
TokenObjectsHolder = { local = "../token_objects_holder" }