[package]
name = 'garage-token'
version = '1.0.0'

[addresses]
token_objects = "0x4"
garage_token = "0xcafe"

[dependencies]
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }
